### ISSUE TITLE
the saved file lost audio track

### ISSUE THREAD

**Issue by CharlesChou73** [Sagnac/streamsave#11]
the file info on stream
![image](https://github.com/Sagnac/streamsave/assets/16950543/285615ca-2738-4e6d-994a-5c914ed32004)

the file info downloaded
![image](https://github.com/Sagnac/streamsave/assets/16950543/5186587a-080a-4859-b8c6-848e37ccbf99)

My operation:
continious mode, ctrl+Z to start dumping, and ctrl+X to end dumping

glad to provide more info if needed

**Comment by Sagnac** [comment]
Could you post the log?

**Comment by CharlesChou73** [comment]
> Could you post the log?

[mpv.log](https://github.com/Sagnac/streamsave/files/13464108/mpv.log)

**Comment by Sagnac** [comment]
I don't see a write request in that log; are you sure you dumped the cache while outputting the log file?

In any case, is the audio track included if instead of using the script you run
```
async dump-cache 0 no file.mp4
```
either through the [console](https://mpv.io/manual/master/#console) or with a keybind?

**Comment by CharlesChou73** [comment]
I used key bind, ctrl+Z to start write, ctrl+X to stop, maybe I shouldn't use ctrl+X to stop?

> I don't see a write request in that log; are you sure you dumped the cache while outputting the log file?

I'm sure, here's what I did:
a. del the mpv log file
b. open a stream video via mpv
c. ctrl+Z to start dumping
d. ctrl+X to stop it
e. exit mpv
then I got a muted video file, and the log file.

> In any case, is the audio track included if instead of using the script you run
> 
> ```
> async dump-cache 0 no file.mp4
> ```
> 
> either through the [console](https://mpv.io/manual/master/#console) or with a keybind?

ran the script in mpv console, it printed this:
![Snipaste_2023-11-27_17-01-31](https://github.com/Sagnac/streamsave/assets/16950543/e5147c4b-8d7c-434d-a4be-2339a05b1b4b)
and got the same muted file (the same size in byte).

**Comment by CharlesChou73** [comment]
I read the "dump-cache" part of mpv wiki, and tried to run the followed script in console:
```
dump-cache 0 10 f:/file.mp4
```
then I got a video file with no audio.

So, I think there's something wrong with the mpv "dump-cache" command?

**Comment by Sagnac** [comment]
This script wraps `dump-cache` so if this issue happens when not using streamsave and instead using `dump-cache` directly in mpv then yes it's potentially a problem with mpv. I still don't see the recorder being initialized in your log so if you report it on their issue tracker I would recommend you produce another log file while also running mpv with `--no-config` from the command line.
