### ISSUE TITLE
streamsave ffmpeg error

### ISSUE THREAD

**Issue by LinuxOpa** [Sagnac/streamsave#5]
mpv https://www.2ix2.com/rtl-live/
 (+) Video --vid=1 (h264 1024x576 25.000fps)
 (+) Audio --aid=1 (aac 2ch 48000Hz)
AO: [pulse] 48000Hz stereo 2ch float
VO: [gpu] 1024x576 yuv420p

ctrl-z:

Cache dumping started.
[ffmpeg] mp4: Tag [15][0][0][0] incompatible with output codec id '86018' (mp4a)
[recorder] Writing header failed.
Cache dumping stopped due to error.

mpv 0.33.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Thu Nov 26 06:59:44 UTC 2020
FFmpeg library versions:
   libavutil       56.60.100
   libavcodec      58.112.103
   libavformat     58.64.100
   libswscale      5.8.100
   libavfilter     7.90.100
   libswresample   3.8.100
FFmpeg version: git-2020-11-22-9208b72

**Comment by Sagnac** [comment]
This issue was fixed in mpv a few months ago; upgrading to the latest mpv (either git or v0.34.0) should fix it. Alternatively you can try one of the workarounds documented [here](https://github.com/Sagnac/streamsave#known-issues) if you wish to keep using an older version of mpv.
